### PR TITLE
style(Validation): improve typescript support

### PR DESCRIPTION
**Pull request by Zoltu**
Improve type information for usage in TypeScript.

### CODE REVIEW

**Comment by PWKad** [comment]
Hi Zoltu can you fix the commit messages to match the standard?  As always this is to help with our changelog generation.

Thanks again for the contribution!

**Comment by Zoltu** [comment]
Do you have a link to where I can see the standard for commit messages?  I don't see a contributor guide in the readme for this repo...

**Comment by PWKad** [comment]
https://github.com/aurelia/validation/blob/master/CONTRIBUTING.md

**Comment by Zoltu** [comment]
@PWKad Do all of the commits need to match the standard or just the PR (which will end up being the merge commit)?

**Comment by Zoltu** [comment]
Done.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!

**Pull request closed without merging**
