### PR TITLE
fixes #166 - TypeError: Cannot read property 'classList' of null

### LINKED ISSUE #166: TypeError: Cannot read property 'classList' of null
*Overview*: There is an error in console 
> TypeError: Cannot read property 'classList' of null

when using default viewStrategy
and validatable input has less than 5 parents (constant in code https://github.com/aurelia/validation/blob/master/src/strategies/twbootstrap-view-strategy.js#L12)
and input doesn't have a parent `.form-group` that `TWBootstrapViewStrategyBase` is looking for. 
capture

*Motivation for change*: waste less developers time by adding helpful log message.

When there are more than 5 parents, then currently there are no error or warning in console related to it and validation messages are just not shown to the user. Developer needs to start debugging, why validation messages are not shown.

When there are less than 5 parents, then the error message doesn't say anything meaningful - developer needs to start debugging.

*Version*: aurelia validation 0.4.0 (current latest)

*Proposal*: Instead of error (that doesn't say much useful) it would be better to add logging message. To avoid big changes, I'd suggest logging with warn level, even tough probably not having a form group is error made by the developer.

### PR DESCRIPTION
**Pull request by atsu85**
As a result of this pull request You'll see a warning in console when form-group is not found with related input as seen here:
capture

### CODE REVIEW

**Comment by atsu85** [comment]
Please merge this pull request to resolve https://github.com/aurelia/validation/issues/166

**Comment by nomack84** [comment]
@PWKad since it was decided to refactor the validation component in order to remove template based code, this PR can be closed.

**Comment by PWKad** [comment]
@atsu85 I'm merging this in to a chore branch that will be the starting point for the templating-validation repository. Thanks for the contribution!

**Comment by PWKad** [comment]
Merged in to `templating-validation`

**Comment by atsu85** [comment]
thanks, i'll add the reference to the corresponding commit in templating-validation repository:
https://github.com/aurelia/templating-validation/commit/570ea0834f7eb43e264b12108cae2763e44ed385

**Pull request closed without merging**
