### PR TITLE
Fix istanbul bug

### PR DESCRIPTION
**Pull request by saqibnoorani**
https://github.com/aurelia/testing/issues/94#

### CODE REVIEW

**Comment by bigopon** [comment]
@saqibnoorani it is difficult to merge or even proceed this PR without any test, or even the comment. Could you please help with at least adding the test based on the examples innthe linked issue?

**Comment by saqibnoorani** [comment]
@bigopon I have included the test scenario where in the old regex fails.

**Comment by fkleuver** [comment]
This makes sense to me. Might also solve some other rare issues.
I don't see how this can do any harm so since the test passes, as far as I'm concerned we should be good.
Thanks @saqibnoorani

**Comment by Sayan751** [comment]
@saqibnoorani Thanks for the fix. I will keep this in mind for AU2 :)

**Comment by fkleuver** [comment]
@bigopon do you think this is good to go?

**Comment by bigopon** [comment]
Yes. I think if any folks complain, we will fix it by exporting a way to make the parser override-able. Its my biggest concern for this, but it shouldnt break any

**Pull request merged**
