### PR TITLE
New tests

### PR DESCRIPTION
**Pull request by jods4**
Demonstrates incorrect behaviour of computedFrom.

### CODE REVIEW

**Comment by PWKad** [comment]
@jods4 @jdanyow is helping to look in to these issues at the moment to figure out the best way to proceed, thanks for your patience.

**Comment by jods4** [comment]
I fixed almost all failing tests by simply adding a `TaskQueue` in `ObserverLocator` ctors. Basically, if you're not Chrome you fallback from `Object.observe` to aurelia setters, which require the `TaskQueue` to work.

Do you want me to add this to the PR?

I have 4 tests still failing in IE, but that requires additional investigations.

**Comment by jods4** [comment]
More info about the remaining failing tests in IE: some tests are very fragile and depend on specific `setTimeout` timings (I had this problem as well for the two tests included in this PR). Depending on the browser, timer resolution, availability of Promises, availability of `Object.observe`,  number of validations [...] the timings used in some tests can easily fail, sometimes erratically.

This is not good but I made some intervals larger so that they seem to always pass on my machine. Again I could add the changes to this PR if you want.

There is one last test that fails, but I don't understand why and I don't have the time to dig deep in debugging. I'm opening an issue about it: #159.

**Comment by jdanyow** [comment]
@jods4 thanks for working on this.  For the timer intervals you could set the ObserverLocator's `dirtyChecker.checkDelay` property.  The default is 120 but I set it much lower in unit-test scenarios and use a constant that is 20ms longer for all the setTimeouts in the tests.

**Comment by jods4** [comment]
@jdanyow I don't think the dirty checker is involved here. It's simple properties so aurelia should use instrumented setters that immediately queue a notification as a microTask in a TaskQueue. 

But there are a lot of moving pieces here because aurelia-validation makes extensive use of Promises, which are all polyfilled as setImmediate at best + there is sometimes a debouncer involved (for computed properties) + aurelia's own TaskQueue uses various scheduling techniques (but -- surprisingly -- never `setImmediate`?)... 
Each scheduling incurs a delay that is hard to define precisely, times an unpredicatable number of Promises & co, so when you sum them all... yeah hard to predict.

I think the situation might be a lot better in Chrome or Edge because of native Promise support, which should be queued as micro-tasks with 0 execution delay.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!

**Pull request closed without merging**
