### PR TITLE
refactor(ValidationViewStrategy): pull apart view strategies

### PR DESCRIPTION
**Pull request by mbroadst**
The main goal of this refactoring is to pull apart the existing
ValidateCustomAttributeViewStrategy into its component parts, and
provide a means to support multiple strategies. Specifically:

  - ValidateCustomAttributeViewStrategy => ValidationViewStrategy
  - Move bootstrap specific view strategy to its own file
  - Update tests accordingly

**NOTE:** There is more work to be done here (specifically that twbootstrap is the default and embedded in the configuration, so this is less modular per se), but this is mostly meant to be a starting point for a discussion.

### CODE REVIEW

**Comment by JeroenVinke** [comment]
should be merged together with https://github.com/aurelia/validation/pull/144

**Comment by mbroadst** [comment]
@JeroenVinke thanks for the fix!

**Comment by PWKad** [comment]
About to merge this one - I'm going to fix the two lint issues but keep in mind it's best to run gulp lint as well before PRing if you get a chance.  Thanks again!

**Comment by mbroadst** [comment]
@PWKad I had included a travis-ci YML file way back when for aurelia-cli. Perhaps it wouldn't hurt to include .travis.yml files for all the aurelia projects simply to run linting and similar sanity checks? This way we'd know very quickly if there were such problems (_in the PR_), even if the actual CI runs happen somewhere else at a later point

**Comment by PWKad** [comment]
Yeah I think @AshleyGrant finishing up CI integration at the moment so we'll hold off until then to include it.

**Comment by zephyrweb** [comment]
Running into issues extending TWBootstrapViewStrategy. I think TWBootstrapViewStrategyBase needs to be exported, like it kinda was originally:

https://github.com/aurelia/validation/commit/ae3aee27f0150cc214ac4d11d7ec8880c06a088d#diff-1fdf421c05c1140f6d71444ea2b27638R10

**Pull request merged**
