### PR TITLE
Remove postinstall script

### PR DESCRIPTION
**Pull request by B3zo0**
This pr removes the post install script from the package.json. It is necessary if you updated your npm to version 5. This caused issues like: #445 #448 #447
After removing the postinstall script npm install works fine.

### CODE REVIEW

**Comment by B3zo0** [comment]
A little explanation why the install happening in uninstall: https://github.com/npm/npm/issues/16863

**Comment by jdanyow** [comment]
thanks for the PR! I've added this change along with some additional package chores. Next release should resolve this.

**Comment by loaded02** [comment]
When will the release happen?

**Comment by loaded02** [comment]
Thx! That was quick.

**Pull request closed without merging**
