### PR TITLE
Rule dependencies #279 

### PR DESCRIPTION
**Pull request by dkent600**
This PR addresses the use case described in #363 by adding a `FluentRulesGenerator` as an alternative to the combination of `FluentRules` and `FluentRulesCustomizer`.  `FluentRules` and `FluentRulesCustomizer` are still supported, for backwards compatibility.

This PR also, as an effortless side-effect, addresses #400, though I note that #400 was recently addressed separately.  The code added for #400 could probably be discarded.

Use case before this PR:

```
let ensureApi: { ensure: (propertyName: string) => FluentRules<any, any> } = ValidationRules;

for (let property of formSchema.properties) {

    if (this.requiresValidation(property, formSchema)) {

        let ruleApi: { satisfiesRule: (name: string, ...args: any[]) => FluentRuleCustomizer<any, any> } =
            ensureApi.ensure(property.name).displayName(property.description);

        if (property.required) {
            ruleApi = ruleApi.satisfiesRule("required");
        }

        if (property.minLength !== undefined) {
            ruleApi = ruleApi.satisfiesRule("minLength", property.minLength);
        }
        ensureApi = ruleApi as FluentRuleCustomizer<any, any>;
    }
}
return ensureApi;
```

The use case after the PR:

```
let ruleGenerator: FluentRulesGenerator<any> = ValidationRules.CreateFluentRulesGenerator();

for (let property of formSchema.properties) {

    if (this.requiresValidation(property, formSchema)) {

        ruleGenerator.ensure(property.name).displayName(property.description);

        if (property.required) {
            ruleGenerator.satisfiesRule("required");
        }

        if (property.minLength !== undefined) {
            ruleGenerator.satisfiesRule("minLength", property.minLength);
        }
    }
}
return ruleGenerator;

```

### CODE REVIEW

**Comment by jdanyow** [comment]
Apologies for the delay reviewing this!

Lot of breaking changes here. We just got to 1.0. Would it be possible to build something on top of the existing fluent APIs without breaking compat?

**Comment by dkent600** [comment]
@jdanyow  It *is* based on the current API, and the current API continues to work as before.  I'm not aware that it breaks anything.  All of the exist unit tests run unaltered.  In other words, this feature adds to, rather than replaces.

Or did I miss something that you spotted?

**Comment by jdanyow** [comment]
Ok, let's get the conflicts resolved and do the work you had mentioned to refocus this on #363 

I was hoping this would be an additive change with no modifications to public interfaces. Maybe this isn't possible or this constraint result in poor developer XP but I'd like to know why. Initially I was thinking this could be done as class that wraps the `ValidationRules` or as a static method on `ValidationRule`- eg `ValidationRules.fromData(...)`. This was explored a little in https://github.com/aurelia/validation/issues/363#issuecomment-253976285. At the time it seemed like the biggest challenge was coming up with a data structure/interface for the rule data. Something that was easy to use and flexible.

Thanks for sticking with this, it's an important feature that many developers have asked for.

**Comment by dkent600** [comment]
@jdanyow 

In response to your comment above, the only non-additive changes that I am aware of are that `ValidationRules.ensure` and `ValidationRules.ensureObject` are now each returning `FluentRulesGenerator<TObject>` instead of `FluentEnsure<TObject>`.
This should only affect someone who is compiling TypeScript and who explicitly expects `FluentEnsure<TObject>`. But I expect that the people most likely to be in that situation are the people mostly likely to welcome this code change, because it will simplify their code, likely absolving them of the need to care what types those two methods are returning (see the code example in the original PR).

**Comment by dkent600** [comment]
@jdanyow 

Please note that I have created a new PR on this, [here](https://github.com/aurelia/validation/pull/443).

**Comment by jdanyow** [comment]
closing- #443 supersedes this one

**Pull request closed without merging**
