### PR TITLE
chore(package): use the external aurelia-tools CLI to build

### PR DESCRIPTION
**Pull request by niieani**
- adds prepare release task: https://github.com/aurelia/validation/issues/357
- blocked on: https://github.com/aurelia/tools/pull/51

### CODE REVIEW

**Comment by jdanyow** [comment]
nice- there's another repo that's using the typescript build we're working on. It's scripts are a bit different because it has html and css assets. I was planning on rolling the changes there into the validation build but I like the approach you've taken with extracting this stuff out into the tools repo.

Here's the other project:

https://github.com/aurelia/ux/blob/master/package.json#L23

What would it take to align both validation and ux on the new tools style typescript build?

**Comment by niieani** [comment]
I think all it would take is adding an optional parameter `--copy-related` to the TS build step that would copy all the non-TS files to the output directories. Pretty trivial I think.

**Comment by EisenbergEffect** [comment]
@niieani @jdanyow Status?

**Comment by niieani** [comment]
@EisenbergEffect we need the tasks from here to be completed before: https://github.com/aurelia/tools/pull/51

If someone wants to take 'em over, feel free to do so.

Afterwards we can start migrating the repos to the new build system.

**Comment by EisenbergEffect** [comment]
@jdanyow Is that something you can do? It looks like you had the setup worked out pretty well for validation now.

**Comment by EisenbergEffect** [comment]
Need to sync this up with the other tools PR so we can have a unified setup for all libs.

**Comment by jdanyow** [comment]
closing- new TypeScript plan from team meeting a few weeks ago supersedes this.

**Pull request closed without merging**
