### PR TITLE
Typescript d.ts support

### PR DESCRIPTION
**Pull request by nomack84**
This PR add support for generating `d.ts` files during the building process. I needed to fix a couple of issues related to imports using `*`, which for some reason I don't know broke the build. 
By default I've added the `en-US` locale in the build which is the more logical. 
I hope this helps. Now is time to start adding types to classes.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@janvanderhaegen Please review and merge as soon as you can to help out the TS developers :) CLA for @nomack84 is verified.

**Comment by JeroenVinke** [comment]
Great! The generated d.ts is invalid however. Look at these lines: https://github.com/nomack84/validation/blob/ec4e103dc5f4d4905314aa3ae99e42df4fb7ead1/dist/amd/aurelia-validation.d.ts#L6-L15

There are no exported modules like `aurelia-validation/validation/utilities`, so you get errors on those lines

**Comment by janvanderhaegen** [comment]
Being a TS developer myself I'm excited to move forward with this!

I've merged #121, @JeroenVinke could you go forward with step 3&4, or let me know if you need anything from me?

I'm hesitant about the locale changes. What are our options? I've opened #125 to discuss. :)

**Comment by nomack84** [comment]
@janvanderhaegen It's me the one that made the PR, I know you were expecting it from @JeroenVinke but I did it first, hehehe. Today I'll work on steps 3&4 to get this merged as soon as possible.

**Comment by nomack84** [comment]
@JeroenVinke I'm not sure how we should handle the translation files. Is it really recommended to have all the translation in the build? I've never seen that. What I've always have seen is that you include a default language, which is always English, and let the developer choose other languages depending on their needs.

**Comment by nomack84** [comment]
@JeroenVinke Can you make a PR against my repo so we merge this with valid TS generated code. I think for the moment we should skip step for until we decided what's best. Discussion here #125 will help. But step 3 can be did it before merging this.

**Comment by JeroenVinke** [comment]
Yes, perhaps we can exclude the resources from being concatenated during build, so that the resources  will still be loaded async. Will have to try this though. The ideal solution would be to follow the other aurelia repositories' setup as close as possible. That way future changes to the build process of these repositories will be easier to apply to aurelia-validation.

Another issue is that when the files are concatenated, `aurelia.globalResources()` will no longer be working (https://github.com/aurelia/validation/blob/master/src/index.js#L18) because the file `validation/validate-custom-attribute.js` no longer exists

**Comment by nomack84** [comment]
@JeroenVinke I'm agree with loading different locales async, I'm thinking this can be done during config time by setting the locale for validation and having `en-US` as fallback. This way we can exclude the en-US from the build a load it async as with other langs. 
And of course we should align as much as possible with the build process from other modules. The only difference we have is the `resources` folder, but if load it async I don't see any problem at all in the build process.

**Comment by nomack84** [comment]
@janvanderhaegen you haven't merged #121 Please do it so I can run the tests

**Comment by JeroenVinke** [comment]
I don't think bundling the `src/validation` files and not the `src/resources` files is going to work because the resources are importing the utilities class: https://github.com/aurelia/validation/blob/master/src/resources/bg-BG.js#L1. The utilities class does not exist when it's bundled.

**Comment by JeroenVinke** [comment]
There is a different approach we can take, will make a PR for this

**Comment by mbroadst** [comment]
FYI #121 hasn't been merged yet :smile:

**Comment by PWKad** [comment]
@JeroenVinke @nomack84 We really need you all to have a unified front on the .d.ts files - can you get together to decided which PR is best to merge?  If we need an arbitrator let me know and I'm sure @cmichaelgraham can help decide which approach is best, but lets get the type definitions in place ASAP.

Also there were a ton of issues with linting and such that had to be resolved, is it feasible to re-base these changes on top of those?  If not and you all can come up with an agreed upon method I will rebase those changes on these.

**Comment by PWKad** [comment]
@nomack84 I appreciate this PR - due to a bunch of changes with linting I was not able to merge it.  TypeScript definitions should be added now though through another PR.  Thanks again for your help!

**Comment by nomack84** [comment]
@PWKad I understand. Are you currently in charge of this repo?

**Comment by PWKad** [comment]
For the time being I'm just helping to get everything updated and inline with what an official plugin needs (linting, d.ts, merging PRs, closing issues, etc...) so hopefully someone with a bit more time will be able to help with direction in feature-work - for now I'm looking to you all in the community who have been more hands on in validation to provide some guidance on what we should tackle and what we should put off.

**Pull request closed without merging**
