### PR TITLE
Small typo in i18n ValidationMessageProvider usage example

### PR DESCRIPTION
**Pull request by abeven**
Casing was off and example did not work as-is.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@abeven Can you sign the CLA please?

**Comment by abeven** [comment]
Not sure what's happening with the CLA assistant but I had signed it before, tried again when I realized it thought I hadn't signed, and just now again it still says that it's been already signed. Any workarounds?

image

**Comment by EisenbergEffect** [comment]
Is there any chance that you have different email addresses associated with your Github account?

**Comment by jdanyow** [comment]
@EisenbergEffect it doesn't look like I have access to do this. Could you try:

>go to repo settings -> webhooks -> find under 'Recent Deliveries' the call for the given PR and click on 'Redeliver'-button
https://github.com/cla-assistant/cla-assistant/issues/159#issuecomment-249132719

**Comment by EisenbergEffect** [comment]
I manually confirmed it in our master list (easier than finding the right delivery).

**Pull request merged**
