### PR TITLE
feat(resources): create ja-JP

### PR DESCRIPTION
**Pull request by shingos**

### CODE REVIEW

**Comment by PWKad** [comment]
@EisenbergEffect cla check

**Comment by EisenbergEffect** [comment]
@PWKad The CLA is confirmed. @shingos Thank you for this contribution!

**Comment by PWKad** [comment]
@shingos Sorry just noticed that the `src` file is in the wrong format - any way you can adjust this?  This should look similar to this - https://github.com/aurelia/validation/pull/188/files

**Comment by shingos** [comment]
@PWKad Sorry. Is this correct?

**Pull request merged**
