### PR TITLE
Updated view strategy documentation

### PR DESCRIPTION
**Pull request by fragsalat**

### CODE REVIEW

**Comment by PWKad** [comment]
@fragsalat Thanks for the update - I need to re-merge this back in after CLA check is complete so please don't delete the branch (I've saved local version just in case) - can you please confirm that you've signed our CLA?

**Comment by fragsalat** [comment]
@PWKad I won't delete the branch for now. Sry but what do you mean with CLA?

**Comment by PWKad** [comment]
The contributing guidelines in each repo detail how to sign CLA so we can accept your commits and prs

**Comment by fragsalat** [comment]
Done

**Comment by PWKad** [comment]
@EisenbergEffect Can you confirm CLA please?

**Comment by EisenbergEffect** [comment]
@PWKad CLA confirmed.

**Comment by miroslavpopovic** [comment]
@PWKad This pull request seems to be merged to master, but [Intro.md](https://github.com/aurelia/validation/blob/master/doc/Intro.md) file is still unchanged. Not sure why... A SO user created a question today using the old config - http://stackoverflow.com/questions/33934767/aurelia-validation-no-message-shown-on-failed-validation

**Pull request merged**
