### PR TITLE
refactor(All): use new core APIs, use rollup to build

### PR DESCRIPTION
**Pull request by bigopon**
The distribution bundle can now be simplified down to a several files:

new-build-validation

And all external imports from `tslib` are declared as import instead of inline'd declaration

@jdanyow

### CODE REVIEW

**Comment by jdanyow** [comment]
this looks awesome! I'll take a more in depth look later this week.

**Comment by bigopon** [comment]
ping @jdanyow

**Comment by jdanyow** [comment]
@bigopon I'm going to try to get this in this weekend. Apologies for the loooong delay!

Could you remove the `/dist/*` files from the PR? Something like:

```bash
git clone https://github.com/bigopon/aurelia-validation
cd aurelia-validation
git reset --soft HEAD~1
git reset
rm -rf dist
git checkout -- dist
git add .
git commit -m "... commit message ..."
git push -f
```

**Comment by bigopon** [comment]
@jdanyow I'm not so sure about specifying helpers from `tslib` like `__decorate` as external, it may break existing app that don't have `tslib` install (rarely though). So I inlined them, small enough though.

**Comment by jdanyow** [comment]
:fire::fire::fire::fire::fire::fire::fire::fire::fire:v

**Pull request merged**
