### PR TITLE
chore(docs): correct typo

### PR DESCRIPTION
**Pull request by MarkHerhold**

### CODE REVIEW

**Comment by PWKad** [comment]
Hi can you please sign our CLA and make sure that the commit message matches the standard?

https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

[Contributing to Aurelia](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md)

Thanks for the contribution!

**Comment by MarkHerhold** [comment]
Done.

**Comment by PWKad** [comment]
@MarkHerhold Sorry to ask but can you also make sure the commit message matches what we need?  it should be formatted something like this (so we can generate the changelog) `chore(docs): correct type`

**Comment by MarkHerhold** [comment]
@PWKad Please pull this in some time. I am tired of looking at it. :)

**Comment by PWKad** [comment]
@MarkHerhold As I mentioned need to correct the commit message in line with the contributions guidelines :)  I can do so but it will not show you as the committer anymore.

**Comment by MarkHerhold** [comment]
@PWKad Oh. I apologize for my stupidity. I changed the PR title, not the commit message. :/

**Comment by MarkHerhold** [comment]
see PR #215

**Comment by PWKad** [comment]
No worries thanks for the help!  We use the commit messages to generate a change log and when they don't match they can break log creation >.<

**Pull request closed without merging**
