### PR TITLE
fixes #168 - makes TWBootstrapViewStrategyBase reusable

### LINKED ISSUE #168: Support reusing code in TWBootstrapViewStrategyBase for custom html/css not related to Twitter Bootstrap
# Motivation
I'm not using Twitter Bootstrap, so the html/css for my application needs to differ slightly compared to bootstrap html/css - for example instead of:
```html
    <div class="form-group">
      <label>
            First Name
      </label>
      <!-- by default validation message is added here -->
      <input type="text" value.bind="firstName" class="form-control" >
    </div>
```
I need following layout:
```html
    <p class="field">
      <label>
            First Name
            <!-- need to add validation message here -->
      </label>
      <input type="text" value.bind="firstName" class="form-control" >
    </p>
```

# Proposal
To be able to reuse TWBootstrapViewStrategyBase, following changes need to be made in that class:
1) export TWBootstrapViewStrategyBase from index.js
2) allow passing following parameters to the constructor (instead of hard-coded values):
* `formGroupClass = "form-group"`
* `validationMsgTagName = "p"`

3) extract code related to inserting `helpBlock` from `findExistingHelpBlock`
4) extract code related to finding existing `helpBlock` from `appendMessageToElement`

### PR DESCRIPTION
**Pull request by atsu85**

### CODE REVIEW

**Comment by atsu85** [comment]
Please merge this pull request to resolve #168 .

**Comment by nomack84** [comment]
@atsu85 you have to squash your commits and sign our CLA before

**Comment by atsu85** [comment]
Hi @nomack84, I signed CLA before sending pull request. 

What is the reason for asking me to squash my commits? I didn't find anything about it from https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#submitting-a-pull-request .
I've created separate commits for each meaningful change/refactor and as a reviewer I'd like to review each change individually to understand the changes faster (to verify that the code still acts the same after refactoring). Also my commits didn't overwrite/fix anything from previous commits, but if You'd like to reivew all changes at once You could do it also: https://github.com/aurelia/validation/pull/169

However if You'll give me a good explanation why squashing is better, I'll do it :) Right now the only thing that came to my mind after thinking about it was automatic generation of the changelog - is this the reason why i should squash my commits?

**Comment by PWKad** [comment]
@atsu85 The reason we want to squash commits as best as possible is so we don't end up with a bunch of extra commits that show up in the changelog - also if something goes wrong it's easier to remove.

We also prefer to not include changes to the `dist` folder until we make a release - this is just to make it easier to review the changes.

**Comment by atsu85** [comment]
@PWKad, thanks for explaining. I've squashed my commits, now the second commit is just a merge - i guess that doesn't need to be squashed, right?

**Comment by nomack84** [comment]
It does. Just one commit please :D

**Comment by nomack84** [comment]
@PWKad @atsu85 since it was decided to refactor the validation component in order to remove template based code, this PR can be closed.

**Comment by atsu85** [comment]
@nomack84, could You provide some more information about the alternative(s) when template based code is removed? I don't think i understand how it is supposed to work? Is the alternative to template based code already possible now or only after refactoring?

**Comment by nomack84** [comment]
@atsu85 I know little about this, but what I know is that there are plans to move the template handling related code to a different repo, similar to https://github.com/aurelia/templating-router & https://github.com/aurelia/templating-binding
@PWKad is the right guy to explain this, as he is the one in charge of this stuff.

**Comment by nomack84** [comment]
@atsu85 it won't be removed, it'll be refactored to a different repo, outside of the main validation plugin

**Comment by atsu85** [comment]
@nomack84 so if this is correct that 
>  it won't be removed, it'll be refactored to a different repo

then i don't see why this pull request should be closed - the fact that some of the functionality will at some point be moved elsewhere doesn't make any difference regarding this change as far as I understand. Please do correct me if I'm wrong.

**Comment by nomack84** [comment]
@atsu85 the problem is that the refactoring has already began. I think it'll be hard to merge this PR if the files the PR is modifying doesn't exist anymore. 
Take a look: https://github.com/aurelia/validation/commits/refactor/remove-dom-manipulation

**Comment by atsu85** [comment]
Ok, so what You are really suggesting with
> this PR can be closed

is to abort this pull request and let me implement the same thing in another repo (or branch of this repo if i'm fast enough) based on the code that is already refactored?

**Comment by nomack84** [comment]
Exactly. :smile:

**Comment by atsu85** [comment]
Ok, fair enough. Just that i understand following
>this PR can be closed

as "this PR isn't needed any more" without explanation and the first explanation that comes to mind is that "the same thing is already taken care of (or will be taken care by someone else)".

Anyway, thanks for taking the time to clarify it :)

**Comment by PWKad** [comment]
Hang tight still going to port the code over so dont close yet ill explain in a bit.  Appreciate the contribution

**Comment by PWKad** [comment]
@atsu85 I'm merging this in to a chore branch that will be the starting point for the templating-validation repository.  Thanks for the contribution!

**Comment by PWKad** [comment]
Merged in to `templating-validation`

**Comment by atsu85** [comment]
Thanks, I'll add the reference to the commit related to this merge request: 
https://github.com/aurelia/templating-validation/blob/refactor/isolate-dom-manipulation/src/strategies/twbootstrap-view-strategy.js

**Pull request closed without merging**
