### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by CharlesPockert**
Some typos in aurelia-app -> aurelia-main="main", should be aurelia-app="main"

### CODE REVIEW

**Comment by chovy** [comment]
+1

**Comment by janvanderhaegen** [comment]
Assigned @EisenbergEffect  to check CLA

**Comment by JeroenVinke** [comment]
FYI, the bootstrapper of the latest skeleton is now named `aurelia-main` instead of `main`. `Welcome.js` has also changed a bit, for example the `welcome()` function has been renamed to `submit()`. I think that the intro should be updated so it uses code from the latest skeleton release.

**Comment by janvanderhaegen** [comment]
Thanks guys! Thank you for contribution!!! 
I'm shaping up the validation library this weekend and will gladly merge your changes :-)
-- CLA confirmed

**Pull request merged**
