### PR TITLE
For issue #170 type script improvements

### PR DESCRIPTION
**Pull request by atsu85**
Please merge this pull request and run `gulp build` to update dist folder.

This pull request improves generated TypeScript declarations (see #170).

This pull request includes initial work from @stephenlautier (see commit https://github.com/stephenlautier/validation/commit/1ea917b55dc3374b72c233d6bf251520f61c9c9a and https://github.com/stephenlautier/validation/commit/7a5eb63b4d95dd1c7e0044ed0421ce432cc120a2) and my fixes/improvements mentioned in his pull request https://github.com/aurelia/validation/pull/162/files as well other my own improvements on that matter for other methods.

### CODE REVIEW

**Comment by atsu85** [comment]
Forgot to mention, that I've signed the CLA.

@stephenlautier I hope it is OK for You, that I included Your commits (mentioned You and added references to Your original commits to avoid "taking the glory" from You). Could You please confirm that this is OK for You so this pull request could be merged without any legal problems?

**Comment by stephenlautier** [comment]
Noooess... my first contribution to this awesome project! Kidding :). Sure go ahead, thanks for the comments. 

As I stated in some of my type defs I updated mainly what I was more confident about hence that's why I set some of them to any (to not break anyone else by using wrong types or anything).

Cheers :+1:

**Comment by atsu85** [comment]
thanks @stephenlautier for Your contribution and permission to include Your work in this pull request!

> I updated mainly what I was more confident about

Actually I'm also doing just that (or looking up smth from the source if documentation doesn't say enough).

> ... that's why I set some of them to any

When writing real TypeScript I've found it really disturbing when I see `any` type and by accident find out that i can't pass anything as an argument - that way in TypeScript it is always better to avoid adding `any` and wait someone else to add correct type info unless `any` really is the best type annotation for that argument or method return type. 
Unfortunately when using babel-dts-generator there is an error when You specify type as a function with parameters, but don't add parameter types - that is where i sometimes give up and just add `any` when I don't want to spend too much time to figure out actual parameter types. Luckily this problem doesn't affect TypeScript comiler that i'm using most of the time :)

**Comment by stephenlautier** [comment]
Ahh I understand your point. Personally it doesn't bother me much, especially even when contributing to definitely typed they use
```
"noImplicitAny": true,
```
So you always have to give it a type, even when you don't know it. Generally when I see `any` I never threat it as `any` but as not defined. They should add `unknown` instead :p to remove ambiguity between `any` or `any` as in unknown/not set :)

**Pull request merged**
