### PR TITLE
Internet Explorer does not support closest

### PR DESCRIPTION
**Pull request by y2k4life**
Made changes to traverse through the ancestors for the `.form-group` style and then either apply errors or remove them.

### CODE REVIEW

**Comment by Ma3yTa** [comment]
I think better is to use polyfill for it:

```
// Polyfill for Element.closest and Element.matches
// https://github.com/jonathantneal/closest/
(function(ELEMENT) {
    ELEMENT.matches = ELEMENT.matches || ELEMENT.mozMatchesSelector || ELEMENT.msMatchesSelector || ELEMENT.oMatchesSelector || ELEMENT.webkitMatchesSelector;

    ELEMENT.closest = ELEMENT.closest || function closest(selector) {
        var element = this;

        while (element) {
            if (element.matches(selector)) {
                break;
            }

            element = element.parentElement;
        }

        return element;
    };
} (Element.prototype));
```

**Comment by jdanyow** [comment]
agree- better to document the polyfill requirement.

**Comment by y2k4life** [comment]
Why the overhead of a polyfill, when just writing a few lines of code resolves the issue? This is not a broad use of closest. The task at hand is to traverse up the DOM to find a specific class. Instead of adding a simple loop to the code to fulfill a specific task you are asking for a polyfill for a broad purpose.

**Comment by y2k4life** [comment]
I just looked at the document updates. It seems to put the burden on the programmer for something as simple as changing the code. Would you agree that what I proposed would fix the problem and not require a polyfill? I could see a need for the polyfill if `closest` was used in multiple places in multiple files. Could the code not be rewritten so that a polyfill would not be required? I think this falls under the KIS model. The simpler it is to use the more will use it.

**Comment by jdanyow** [comment]
With Aurelia we want to promote writing clean, modern JavaScript code. We're going to use standard APIs with broad browser support that can easily be polyfilled (like [`closest`](https://dom.spec.whatwg.org/#dom-element-closest)). This makes the examples easier to read, especially longer ones like the renderer example we're discussing here. This also "future proofs" the examples and introduces developers to a useful DOM API that they might not have otherwise known about.

The polyfill minified with [uglify](https://skalman.github.io/UglifyJS-online/) is around 235 bytes. The code added in this PR, minified, adds around 305 bytes- so right away the polyfill is a win.

**Pull request closed without merging**
