### PR TITLE
Catalan language, ca-ES, added

### PR DESCRIPTION
**Pull request by dpinart**
Catalan language, ca-ES, added. Volem votar

### CODE REVIEW

**Comment by janvanderhaegen** [comment]
Awesome,
I'm proud to have Catalan in our validation repo!! 
One last request, for legal matters, could you verify [you've signed the contributors license agreement](http://goo.gl/forms/dI8QDDSyKR)?

Thank you so much

J

**Comment by dpinart** [comment]
You're welcome. Thanks for your job and keep pushing this way

**Comment by janvanderhaegen** [comment]
Awesome! Molt apreciat , moltes gràcies

**Comment by dpinart** [comment]
Gràcies a tu i a tots el que feu que programar amb Aurelia sigui tan apassionant. Un català perfecte, per cert

**Comment by JeroenVinke** [comment]
This is breaking the unit tests. There is now transpiled code in the src directory

```
ReferenceError: define is not defined
    at execute (http://localhost:9877/base/src/resources/ca-ES.js:7:7)
    at ensureEvaluated (http://localhost:9877/base/jspm_packages/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:2153:26)
    at Object.Promise.all.then.execute (http://localhost:9877/base/jspm_packages/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:2291:13)
    at doDynamicExecute (http://localhost:9877/base/jspm_packages/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:715:25)
```

**Comment by JeroenVinke** [comment]
fixed in this PR: https://github.com/aurelia/validation/pull/127

**Pull request merged**
