### PR TITLE
fix(viewstrategy) p-element containing validationmessage now toggles display:block/none

### PR DESCRIPTION
**Pull request by Einarsson**
Issue described here:
https://github.com/aurelia/validation/issues/78

Made a quick simple fix to solve it, merge it if you think it's good enough, else throw it. :-)

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@janvanderhaegen I'm wondering if this shouldn't be handled a bit more like the aurelia show behavior does, by adding/removing a class to the element instead? I'd go with this fix for now, but re-evaluate the class-based strategy afterwards. Bear in mind you may  need to account for shadow dom penetration. See the latest version of the show behavior to see how that's done.

**Comment by Einarsson** [comment]
@EisenbergEffect @janvanderhaegen I agree that it would be a more consistent solution to use the class aurelia-hide instead.

However, is it safe to assume that the class aurelia-hide is always available? If it's possible to simply just use it, since the show-behaviour loaded by the templating engine already adds it. Then it's simple to change this fix to make it a more suitable long term solution. It would also take care of the shadow-DOM issue.

**Comment by EisenbergEffect** [comment]
I'm not suggesting to use the aurelia-hide or show itself. Those may not be guaranteed to be present. But the code to do that is simple and small, so I'm suggesting to replicate the idea in this case.

**Comment by Einarsson** [comment]
@EisenbergEffect Like this??

https://github.com/Einarsson/validation/commit/8154acdaccdb607c791f49a54ce82bf77306a481

Let me know if you want me to request it.

**Comment by janvanderhaegen** [comment]
Actually, this is probably already possible with the current implementation.

Could you add this to your CSS and let me know if it worked? If so, I'll update the documentation to suggest this.

```css
p.aurelia-validation-message{
  display: none;
}

div.form-group.has-warning p.aurelia-validation-message
{
  display: block;
}
```

**Comment by janvanderhaegen** [comment]
Also, perhaps we can even be smarter and use

```css
p.aurelia-validation-message{
  display: block;
}
p.aurelia-validation-message:empty{
  display:none;
}
```

**Comment by Einarsson** [comment]
@janvanderhaegen That actually works, didn't think of it. Thank you. :) This kind of behavior should probably still be default though, but adding it to documentation and using this at least solves the problem for now. :+1:

**Comment by janvanderhaegen** [comment]
Hey @Einarsson !
Glad you're back on track.
I'm short for time, but in a week or so I'll be happy to have a solution which comes 'out-of-the-box' and does not require additional css.

Thanks for reporting and the pull requests

Jan

**Comment by EisenbergEffect** [comment]
@janvanderhaegen Just checking in on status of this? Has this been resolved?

**Comment by janvanderhaegen** [comment]
The CSS solution is probably cleaner than an additional code fix, but more steps for installing the plugin. 
Would rather keep this open for a little bit longer, if I may. Upcoming steps in the validation library are splitting out all the 'UI' components so the actual validation can be used server-side, and re-evaluating how the validation hints are being shown (issues with 'if.bind' and foreach, etc).

**Comment by nomack84** [comment]
@PWKad since it was decided to refactor the validation component in order to remove template based code, this PR can probably be closed.

**Comment by PWKad** [comment]
@nomack84 Can you let me know (in your opinion) whether we should carry this commit over to the templating piece?  I'd like to make sure we don't lose anything along the way so trying to do some cleanup now.

**Pull request closed without merging**
