### PR TITLE
feat(I18N): add pt-BR

### PR DESCRIPTION
**Pull request by fabioluz**
:)

### CODE REVIEW

**Comment by PWKad** [comment]
Hi @fabioluz can you please sign our CLA so I can get this merged in?

https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

Thanks for the contribution!

**Comment by fabioluz** [comment]
I'm already signed. Should I sign it again?

**Comment by PWKad** [comment]
No you are good we don't have automated check on CLA so first time for the repo usually double-check :)  Thanks again!

@EisenbergEffect CLA confirmation?

**Comment by EisenbergEffect** [comment]
Confirmed

**Pull request merged**
