### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by JeroenVinke**
https://github.com/aurelia/validation/pull/122 changes the way aurelia-validation is compiled by concatenating all files, and refactoring is needed in order to get this working.

This PR also concatenates all validation files, but does this only to generate the d.ts file. The concatenated file is never outputted. The generated d.ts file is copied to all dist directories (commonjs, amd etc).

A few notes, index.js has to be excluded from the concatenation because it was throwing in a few imports in the generated d.ts which caused it to be invalid. so the configure method in index.js can't be typed using this approach. 

I also don't know what `.pipe(tools.sortFiles()) ` does, but it's throwing an error when enabling it. Everything still works when this is disabled though. https://github.com/aurelia/validation/commit/7579adf14bd0c65e721013fcf44b0749c236cf35#diff-40e62be8220b9aeab02f5a664980bd73R21 Error is here: https://gist.github.com/JeroenVinke/58a108b43eb110e154bd

It's not possible to change the outdir of the babel-dts-generator, so the gulp task is a bit complexer because of this. Currently the d.ts file is outputted to `dist/aurelia-validation/aurelia-validation.d.ts`. This directory is removed at the end of the `build` task, after the definition file has been copied to all dist directories

This is the output if you apply the changes in this PR: [output](http://i.imgur.com/YnH64yZ.png). and this is the generated definition: https://gist.github.com/JeroenVinke/729d9c12f8de7b8396f2

### CODE REVIEW

**Comment by JeroenVinke** [comment]
@janvanderhaegen this PR is basically a quick fix to get typescript support in, so the typescript developers can start using them, and so that the community is able to add the types in the source. This way we won't have to wait for the refactoring of the resources as suggested in https://github.com/aurelia/validation/issues/129.

**Comment by PWKad** [comment]
@JeroenVinke @nomack84 We really need you all to have a unified front on the .d.ts files - can you get together to decided which PR is best to merge?  If we need an arbitrator let me know and I'm sure @cmichaelgraham can help decide which approach is best, but lets get the type definitions in place ASAP.

Also there were a ton of issues with linting and such that had to be resolved, is it feasible to re-base these changes on top of those?  If not and you all can come up with an agreed upon method I will rebase those changes on these.

**Comment by JeroenVinke** [comment]
@PWKad Thanks for dedicating some time on this

The problem with https://github.com/aurelia/validation/pull/122 is that it needs changes to the way translation files are loaded and used (discussed in https://github.com/aurelia/validation/issues/125). This PR is not perfect (eg. stuff in index.js can't be typed), but it doesn't need more changes than you see in this PR. If we can get the necessary changes in to allow for a single file export during build quickly, I vote for https://github.com/aurelia/validation/pull/122, and if not we can use the approach in this PR in the mean time.

**Comment by PWKad** [comment]
@JeroenVinke Understood - I'm in the middle of cleaning up all of the lint issues in the repo that needed to be addressed to allow the TS build tools to run anyway.  Unfortunately this means it's breaking this PR's ability to merge.  In the interest of time the two best solutions I can think of are to wait until those changes are applied and then have this be re-based on top (which is going to be a pain unfortunately due to formatting / spacing issues requiring lots of changes) or I can try to merge it afterwards.  I'm not entirely familiar with TypeScript so if you think you would have the time to do so (I hope to finish with linting issues today) after that we would greatly appreciate it :)

**Comment by JeroenVinke** [comment]
Let me know when I can create a new PR.

**Comment by PWKad** [comment]
@JeroenVinke the linting work is finished, should be stable now.

**Pull request closed without merging**
