### PR TITLE
fix(index): update to latest configuration api

### PR DESCRIPTION
**Pull request by ejsmith**

### CODE REVIEW

**Comment by jadrake75** [comment]
+1 please approve and merge!

**Comment by grischa41277** [comment]
+1 yes, please approve!

**Comment by janvanderhaegen** [comment]
Thank you for the contrib!!!

**Comment by ejsmith** [comment]
Awesome! Are you going to publish a new release for jspm?

**Comment by janvanderhaegen** [comment]
Published.
I'm sorry I haven't had a lot of time to manage this project better lately, but very grateful for having such an active community!

**Pull request merged**
